name: url-shortening-service
services:
  url-shortening-service:
    image: url-shortening-service:latest
    container_name: url-shortening-service
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: st4rdusted
      SPRING_DATASOURCE_PASSWORD: postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=st4rdusted
      - POSTGRES_PASSWORD=postgres